// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC05jvK03COY9zcwAKwxQqw1SCu9tURgo8',
    appId: '1:144480149154:web:24850089d9d0aa49ea41fb',
    messagingSenderId: '144480149154',
    projectId: 'inventorywang',
    authDomain: 'inventorywang.firebaseapp.com',
    storageBucket: 'inventorywang.firebasestorage.app',
    measurementId: 'G-ZDLLH7Z1TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqKuoWCu32LiCorfdUXmALxRr_RsqS1XM',
    appId: '1:144480149154:android:fe2fc7468bbd67f1ea41fb',
    messagingSenderId: '144480149154',
    projectId: 'inventorywang',
    storageBucket: 'inventorywang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZi0e7cJGalvv-0PXpHv57KC2l6W-hE4',
    appId: '1:144480149154:ios:5acaad6da7f60087ea41fb',
    messagingSenderId: '144480149154',
    projectId: 'inventorywang',
    storageBucket: 'inventorywang.firebasestorage.app',
    iosBundleId: 'com.example.logistic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZi0e7cJGalvv-0PXpHv57KC2l6W-hE4',
    appId: '1:144480149154:ios:5acaad6da7f60087ea41fb',
    messagingSenderId: '144480149154',
    projectId: 'inventorywang',
    storageBucket: 'inventorywang.firebasestorage.app',
    iosBundleId: 'com.example.logistic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC05jvK03COY9zcwAKwxQqw1SCu9tURgo8',
    appId: '1:144480149154:web:778f67738097fe3cea41fb',
    messagingSenderId: '144480149154',
    projectId: 'inventorywang',
    authDomain: 'inventorywang.firebaseapp.com',
    storageBucket: 'inventorywang.firebasestorage.app',
    measurementId: 'G-6EESTVZEDV',
  );
}
